name: Run QA Scraper

on:
  push:
  workflow_dispatch:

jobs:
  run-playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install playwright

      - name: Run Scraper - 22f3001098@ds.study.iitm.ac.in
        run: node scraper.js
